# ┌─┐┬ ┬┬─┐┌─┐┬─┐┌─┐  ┌─┐┬─┐┌─┐┌┬┐┌─┐┬ ┬┌─┐┬─┐┬┌─
# ├─┤│ │├┬┘│ │├┬┘├─┤  ├┤ ├┬┘├─┤│││├┤ ││││ │├┬┘├┴┐
# ┴ ┴└─┘┴└─└─┘┴└─┴ ┴  └  ┴└─┴ ┴┴ ┴└─┘└┴┘└─┘┴└─┴ ┴
# A Powerful General Purpose Framework
# More information in: https://aurora-fw.github.io/
#
# Copyright (C) 2017 Aurora Framework, All rights reserved.

branches:
  only:
    - master
    - dev
    - wip
    - linux
    - darwin
    - windows

language: cpp

matrix:
  allow_failures:
    - os: osx

  include:
    - os: linux
      compiler: clang
      sudo: required
      services: docker
    - os: linux
      compiler: gcc
      sudo: required
      services: docker
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang

arch:
  packages:
    - gtk3
    - ninja
    - vulkan-headers
    - glfw-x11
    - glew
    - cmake
    - freeimage
    - libsndfile
    - portaudio
    - doxygen
    - repo
    - lcov
    - python
    - python-pip
    - qt5-tools
    - qt5-base
    - qt5-declarative

  script:
#    - if [[ "$TRAVIS_BRANCH" == "dev" ]]; then yes | repo init -u https://github.com/aurora-fw/manifest.git -m development.xml -b dev; else yes | repo init -u https://github.com/aurora-fw/manifest.git -b $TRAVIS_BRANCH; fi
#    - repo sync
#    - sudo repo forall -c repo start $TRAVIS_BRANCH .
    - if [[ "$TRAVIS_BRANCH" != "master" ]]; then cmake -DCMAKE_BUILD_TYPE=Debug -DAURORA_BUILD_TEST_APPS=ON -DAURORA_TARGET_DOCUMENTATION=ON -DAURORA_CODECOVERAGE=ON .; else cmake -DCMAKE_BUILD_TYPE=Release -DAURORA_CODECOVERAGE=ON .; fi
    #- if [[ "$TRAVIS_BRANCH" != "master" ]]; then cmake -DCMAKE_BUILD_TYPE=Debug -DAURORA_BUILD_TEST_APPS=ON -DAURORA_TARGET_DOCUMENTATION=ON -DAURORA_CODECOVERAGE=ON .; else cmake -DCMAKE_BUILD_TYPE=Release -DAURORA_TARGET_DOCUMENTATION=ON -DAURORA_CODECOVERAGE=ON .; fi
    - make
    - sudo make install
    - make documentation
    - sudo pip install codecov
    - for filename in `find . | egrep '\.cpp'`; 
      do
        gcov -n -o . $filename > /dev/null; 
      done
    - codecov
    #- bash <(curl -s https://codecov.io/bash) #upload to codecov

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      curl -s https://raw.githubusercontent.com/aurora-fw/ci_travis_archlinux/master/arch-travis.sh | bash;
    fi;

notifications:
  email:
    recipients:
      - auroraframework@gmail.com
  on_success: never
  on_failure: always